### ISSUE TITLE
TypeError: build_msa()

### ISSUE THREAD

**Issue by Coke-Zhang** [jlparkI/AntPack#16]
I run the number example, bulid_msa() and assign_cdr_labels() having this error, 
`TypeError: build_msa(): incompatible function arguments. The following argument types are supported:
    1. build_msa(self, arg0: collections.abc.Sequence[str], arg1: collections.abc.Sequence[tuple[collections.abc.Sequence[str], float, str, str]], [/](https://vscode-remote+ssh-002dremote-002btower101.vscode-resource.vscode-cdn.net/)) -> tuple[list[str], list[str]]
  Invoked with types: antpack.numbering_tools.single_chain_annotator.SingleChainAnnotator, list, list, bool  `
  Please give me a suggest, Thanks !

**Comment by jlparkI** [comment]
I think that you probably have version 0.3.5.1 or earlier, right? In version 0.3.5.1 (and earlier), the `build_msa` command only took two arguments, and if you try to run the numbering example with v0.3.5.1 you will indeed get this error. Starting in v0.3.6.1, it takes 3 arguments, the list of sequences and the list of annotations just like in prior versions but also a third argument `add_unobserved_positions` which is either True or False (see the docs).

I would recommend upgrading to v0.3.6.1 in any case, it has some other improvements as well. You can do this using:
```
pip install --upgrade AntPack
```

If you're still having this problem after the upgrade let us know. Thanks!

**Comment by Coke-Zhang** [comment]
Thanks ! I also think it's this issue. I tried checking the version number of the package, but unfortunately, the information is incomplete. 
![20241108-111616](https://github.com/user-attachments/assets/bebed170-efe2-497d-b0fa-b2a5488eddc8)
Now. I use the code to deal with this issues, Thanks!
