### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by shizipo** [jlparkI/AntPack#5]
gcc -pthread -B /home/software/miniconda3.8/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iantpack/ext -I/tmp/pip-build-env-po0wrd9h/overlay/lib/python3.8/site-packages/pybind11/include -I/home/software/miniconda3.8/include/python3.8 -c antpack/ext/aligner.cpp -o build/temp.linux-x86_64-cpython-38/antpack/ext/aligner.o -std=c++11 -fvisibility=hidden -g0 -std=c++11 -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from antpack/ext/aligner.cpp:1:0:
  antpack/ext/aligner.h:126:55: error: array must be initialized with a brace-enclosed initializer
                   "Unexpected AA at conserved position."};
                                                         ^
  antpack/ext/aligner.h:126:55: error: too many initializers for ‘std::array<std::basic_string<char>, 6ul>’
  error: command '/usr/bin/gcc' failed with exit code 1

  ----------------------------------------
  ERROR: Failed building wheel for antpack
Failed to build antpack
ERROR: Could not build wheels for antpack which use PEP 517 and cannot be installed directly

**Comment by jlparkI** [comment]
Looks like this is an error specific to older versions of gcc. At one time, C++11 required double curly braces for array initialization (https://en.cppreference.com/w/cpp/container/array), but not subsequent to the CWG 1270 revision or at any time thereafter. I can will fix this in the next release.

**Comment by shizipo** [comment]
I'm glad to receive your reply so quickly. The above error has been resolved. Thank you very much!

**Comment by shizipo** [comment]
> Looks like this is an error specific to older versions of gcc. At one time, C++11 required double curly braces for array initialization (https://en.cppreference.com/w/cpp/container/array), but not subsequent to the CWG 1270 revision or at any time thereafter. I can will fix this in the next release.
