### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by orangeyan** [jlparkI/AntPack#6]
gcc -pthread -B /home/yanj/miniconda3/envs/Numbering/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iantpack/ext -I/tmp/pip-build-env-nrcl23v7/overlay/lib/python3.8/site-packages/pybind11/include -I/home/yanj/miniconda3/envs/Numbering/include/python3.8 -c antpack/ext/aligner.cpp -o build/temp.linux-x86_64-cpython-38/antpack/ext/aligner.o -std=c++11 -fvisibility=hidden -g0 -std=c++11 -fvisibility=hidden
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
      In file included from antpack/ext/aligner.cpp:1:0:
      antpack/ext/aligner.h:126:55: error: array must be initialized with a brace-enclosed initializer
                       "Unexpected AA at conserved position."};
                                                             ^
      antpack/ext/aligner.h:126:55: error: too many initializers for ‘std::array<std::basic_string<char>, 6ul>’
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for antpack
Failed to build antpack
ERROR: Could not build wheels for antpack, which is required to install pyproject.toml-based projects

My version of GCC is 4.8.5,which support c++11

**Comment by jlparkI** [comment]
Looks like this is an error specific to older versions of gcc. At one time, C++11 required double curly braces for array initialization (https://en.cppreference.com/w/cpp/container/array), but not subsequent to the CWG 1270 revision or at any time thereafter. I can will fix this in the next release.

**Comment by orangeyan** [comment]
> Looks like this is an error specific to older versions of gcc. At one time, C++11 required double curly braces for array initialization (https://en.cppreference.com/w/cpp/container/array), but not subsequent to the CWG 1270 revision or at any time thereafter. I can will fix this in the next release.

thank you~

**Comment by jlparkI** [comment]
I believe this should be fixed in 0.1.5.2, which is now on PyPi. I.e. if you pip install antpack this should work...
